"""Add audit fields to User (created_at, pw_changed_at, pw_expires_at)

Revision ID: bad64bf96870
Revises: ea670e0397f0
Create Date: 2025-04-29 11:25:50.496759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad64bf96870'
down_revision = 'ea670e0397f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pw_changed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pw_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pw_expires_at')
        batch_op.drop_column('pw_changed_at')
        batch_op.drop_column('created_at')

    op.drop_table('login_history')
    # ### end Alembic commands ###
